In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [ ]:
nltk.download('all')

In [ ]:
%cd /content/drive/MyDrive/AI NAVER/NLP

/content/drive/MyDrive/AI NAVER/NLP

In [ ]:
from collections import Counter
import nltk
import string
from nltk.tokenize import word_tokenize
import pandas as pd
import numpy as np
import math

from plotly import __version__
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
import plotly.graph_objs as go
init_notebook_mode(connected=True)

In [ ]:
df_list = []
cities = ['boston', 'chicago', 'la', 'montreal', 'ny', 'sf', 'toronto', 'vancouver']
for city in cities:
    df_tmp = pd.read_pickle('data_scientist_{}.pkl'.format(city))
    df_tmp['city'] = city
    df_list.append(df_tmp)

In [ ]:
df_list[0]

,job_title,company,location,job_description,city
0,Junior Data Scientist,Pacific Life,"- Boston, MA",Purpose of Role:\nAs part of the PLRe Retro Pr...,boston
1,Senior Data Scientist,Invicro,"- Boston, MA 02210 (South Boston area)",Overview:\nThe Senior Data Scientist will be a...,boston
2,Data Scientist,Trillium,"- Boston, MA 02108 (Back Bay-Beacon Hill area)","Now hiring a Data Scientist in Boston, Massach...",boston
3,Data Scientist,ENGIE Insight,"- Boston, MA",ENGIE Impact is accelerating sustainability tr...,boston
4,"Analyst II/Assistant Director, Data Science",Liberty Mutual Insurance,"- Boston, MA 02101",Liberty Mutual’s newly formed Global Risk Solu...,boston
...,...,...,...,...,...
800,Senior Data Analyst,MassMutual,"- Boston, MA",â€<â€<\nMassMutual continues to expand its dat...,boston
801,100% REMOTE Data Scientist- Healthcare Claims/...,CyberCoders,"- Boston, MA 02108 (Back Bay-Beacon Hill area)",100% REMOTE Data Scientist- Healthcare Claims/...,boston
802,Senior Data Scientist-Systems Engineering,Cenergy International Services,"- Cambridge, MA 02139 (Area IV area)",Senior Data Scientist – Systems Engineering\nT...,boston
803,"Analytics, Data Scientist - Artificial Intelli...",CVS Health,"- Boston, MA 02110 (Downtown area)",This role will have the unique opportunity to ...,boston
804,Junior Data Scientist,Pacific Life,"- Boston, MA",Purpose of Role:\nAs part of the PLRe Retro Pr...,boston

In [ ]:
df_list[:10]

In [ ]:
df = pd.concat(df_list).reset_index(drop=True)

In [ ]:
df

,job_title,company,location,job_description,city
0,Junior Data Scientist,Pacific Life,"- Boston, MA",Purpose of Role:\nAs part of the PLRe Retro Pr...,boston
1,Senior Data Scientist,Invicro,"- Boston, MA 02210 (South Boston area)",Overview:\nThe Senior Data Scientist will be a...,boston
2,Data Scientist,Trillium,"- Boston, MA 02108 (Back Bay-Beacon Hill area)","Now hiring a Data Scientist in Boston, Massach...",boston
3,Data Scientist,ENGIE Insight,"- Boston, MA",ENGIE Impact is accelerating sustainability tr...,boston
4,"Analyst II/Assistant Director, Data Science",Liberty Mutual Insurance,"- Boston, MA 02101",Liberty Mutual’s newly formed Global Risk Solu...,boston
...,...,...,...,...,...
4134,Intermediate Accountant (Maternity Leave),Tantalus Labs Ltd.,"- Vancouver, BC",The Company\nTantalus Labs is committed to Sun...,vancouver
4135,Human Resources Generalist,STEMCELL Technologies,"- Vancouver, BC",Job Description Summary\nThe Human Resources G...,vancouver
4136,Data Developer - RACE21,Teck Resources Limited,- British Columbia,"Location: Vancouver, BC, CA\nWith a strong his...",vancouver
4137,Data Scientist,Annex Consulting Group,"- Metro Vancouver Regional District, BC",Data Scientist\n\nContract- 9 months with exte...,vancouver
4138,Environmental Lead Scientist,SynergyAspen Environmental Inc.,"- Port Moody, BC",We are currently recruiting for an Environment...,vancouver

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4139 entries, 0 to 4138
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   job_title        4139 non-null   object
 1   company          4139 non-null   object
 2   location         4139 non-null   object
 3   job_description  4139 non-null   object
 4   city             4139 non-null   object
dtypes: object(5)
memory usage: 161.8+ KB

In [ ]:
df.shape

(4139, 5)

In [ ]:
msk = df['city'] == 'la'
df.loc[msk, 'city'] = 'los angeles'

msk = df['city'] == 'ny'
df.loc[msk, 'city'] = 'new york'

msk = df['city'] == 'sf'
df.loc[msk, 'city'] = 'san francisco'

In [ ]:
print(df.shape)
df = df.drop_duplicates(subset=['job_description', 'city', 'job_title'])
print(df.shape)

(4139, 5)
(2681, 5)

In [ ]:
df.isna().sum()

job_title          0
company            0
location           0
job_description    0
city               0
dtype: int64

In [ ]:
df

,job_title,company,location,job_description,city
0,Junior Data Scientist,Pacific Life,"- Boston, MA",Purpose of Role:\nAs part of the PLRe Retro Pr...,boston
1,Senior Data Scientist,Invicro,"- Boston, MA 02210 (South Boston area)",Overview:\nThe Senior Data Scientist will be a...,boston
2,Data Scientist,Trillium,"- Boston, MA 02108 (Back Bay-Beacon Hill area)","Now hiring a Data Scientist in Boston, Massach...",boston
3,Data Scientist,ENGIE Insight,"- Boston, MA",ENGIE Impact is accelerating sustainability tr...,boston
4,"Analyst II/Assistant Director, Data Science",Liberty Mutual Insurance,"- Boston, MA 02101",Liberty Mutual’s newly formed Global Risk Solu...,boston
...,...,...,...,...,...
4132,Human Resources Coordinator,STEMCELL Technologies,"- Vancouver, BC",Job Description Summary\nThe Human Resources C...,vancouver
4133,Technical Sourcing Recruiter,"AMZN CAN Fulfillment Svcs, ULC","- Vancouver, BC",Bachelor’s degree\nYou have 3+ years of corpor...,vancouver
4134,Intermediate Accountant (Maternity Leave),Tantalus Labs Ltd.,"- Vancouver, BC",The Company\nTantalus Labs is committed to Sun...,vancouver
4135,Human Resources Generalist,STEMCELL Technologies,"- Vancouver, BC",Job Description Summary\nThe Human Resources G...,vancouver
4137,Data Scientist,Annex Consulting Group,"- Metro Vancouver Regional District, BC",Data Scientist\n\nContract- 9 months with exte...,vancouver

In [ ]:
df['job_description'].iloc[1]

'Overview:\nThe Senior Data Scientist will be an imperative member of Invicro’s growing AI Team. We are looking for well-organized, talented people with a deep knowledge in programming, data processing, automation, statistics and machine learning. The Senior Data Scientist uses mathematics, statistics, modeling, analysis, and technology to transform high volumes of complex imaging data into advanced, interpretable analytic solutions.\n\nResponsibilities:\nDrive the collection, organization, coordination and governance around internal and external data resources.\nDevelops, maintains, and collects structured and unstructured data sets for analysis and reporting.\nCreative thinking in reports, projections, models, and presentations to support Invicro’s Imaging Analysis strategy and AI initiative.\nProvide influence on department strategy around data science and machine learning.\nMaintain awareness of the resources and advances in artificial intelligence applied to biomedical problems, in particular resources relevant to pathology, neurology or drug development.\nDevelop and maintain unit and system-level regression testing.\nContribute to collaborative science incorporating machine learning / AI into clinical goals.\nDevelop and verify easy to use reference datasets that facilitate machine learning/AI research, testing and application deployment\nMentor junior data scientists.\n\nQualifications/Skills:\nMaster’s degree in Data Science or related field with 3-5+ years of industry or academic experience\nDirect experience in an Engineering / Data Science environment preferred\n5+ years of programming/scripting experience with a variety of languages including but not limited to python, R and C++. The ability to program with keras and the low-level tensor flow API.\nDeep, practical knowledge of using the training, testing and validation paradigm to drive progress\nDemonstrated commitment to reusable/repurposable data organization and software\nStrong intuitions about data modeling and testing and how to overcome common obstacles\nIn-depth knowledge of a biomedical or scientific application area and experience with applying deep learning to problems in this area\n\nInvicro is an equal opportunities employer and positively encourages applications from suitably qualified and eligible candidates regardless of sex, race, disability, age, sexual orientation, gender reassignment, religion or belief, marital status, or pregnancy and maternity.'

In [ ]:
word_tokenize(str(df['job_description'].iloc[12]))

['What',
 'you',
 'will',
 'be',
 'doing',
 'As',
 'a',
 'member',
 'of',
 'the',
 'data',
 'science',
 'team',
 ',',
 'you',
 'will',
 'be',
 'working',
 'alongside',
 'our',
 'technical',
 'experts',
 'and',
 'your',
 'role',
 'will',
 'be',
 'key',
 'to',
 'roll-out',
 'our',
 'different',
 'solutions',
 'to',
 'the',
 'clients',
 '.',
 'Your',
 'day-to-day',
 ':',
 'Set-up',
 'and',
 'deploy',
 'in',
 'production',
 'the',
 'data',
 'processing',
 'pipelines',
 'of',
 'our',
 'clients',
 ',',
 'including',
 'data',
 'reception',
 'in',
 'batches',
 'or',
 'in',
 'real-time',
 ',',
 'data',
 'cleaning',
 ',',
 'information',
 'extraction',
 ',',
 'calibration',
 'of',
 'fraud',
 'detection',
 'models',
 ',',
 'etc',
 '.',
 'R',
 '&',
 'D',
 'for',
 'product',
 'development',
 'and',
 'innovation',
 '(',
 'through',
 'machine',
 'learning',
 ',',
 'image',
 'analysis',
 ',',
 'NLP',
 ',',
 'trend',
 'analysis',
 ',',
 'chatbots…',
 ')',
 'Work',
 'closely',
 'with',
 'our',
 'clients',
 'to',
 'understand',
 'their',
 'needs',
 ',',
 'their',
 'feedback',
 'to',
 'improve',
 'our',
 'solutions',
 'Work',
 'closely',
 'with',
 'the',
 'sales',
 'team',
 'for',
 'prospects',
 'demo',
 '(',
 'and',
 'yes',
 ',',
 'that',
 'includes',
 'traveling',
 'worldwide',
 '!',
 ')',
 'Training',
 'of',
 'junior',
 'Data',
 'scientists',
 'Your',
 'profile',
 'You',
 'have',
 'a',
 'degree',
 'in',
 'mathematics',
 'and',
 'statistics',
 '(',
 'a',
 'specialization',
 'in',
 'machine',
 'learning',
 'and/or',
 'Big',
 'Data',
 'is',
 'a',
 'plus',
 ')',
 'You',
 'are',
 'familiar',
 'with',
 'an',
 'object-oriented',
 'programming',
 'language',
 'and',
 'are',
 'willing',
 'to',
 'learn',
 'a',
 'new',
 'one',
 '(',
 'C',
 '#',
 ')',
 'You',
 'combine',
 'strong',
 'analysis',
 'with',
 'synthesis',
 'abilities',
 'and',
 'are',
 'not',
 'afraid',
 'to',
 'deal',
 'with',
 'the',
 'details',
 'You',
 'can',
 'write',
 'quality',
 'production',
 'code',
 'You',
 'are',
 'comfortable',
 'dealing',
 'with',
 'clients',
 'You',
 'are',
 'fluent',
 'in',
 'English',
 '(',
 'native',
 'speaker',
 'ideally',
 ')',
 'with',
 'degree',
 'or',
 'work',
 'experience',
 'in',
 'the',
 'US',
 'Recruitment',
 'process',
 '1',
 '.',
 'Screening',
 'Conversation',
 'with',
 'a',
 'recruiter',
 '(',
 '30-45',
 'min',
 ')',
 '2',
 '.',
 'Tech',
 'Screening',
 '&',
 'face',
 'to',
 'face',
 'Interview',
 '(',
 '2',
 'hours',
 ')',
 '3',
 '.',
 'Last',
 'interview',
 'with',
 ':',
 'HR',
 '(',
 '30',
 'min',
 ')',
 'Team',
 'Lead',
 'Interview',
 '(',
 '30',
 'min',
 ')',
 'Perks',
 'and',
 'benefits',
 'Brand',
 'new',
 'office',
 'in',
 'the',
 'Financial',
 'District',
 'of',
 'Boston',
 'Business',
 'trip',
 'top',
 'Paris',
 'Team',
 'building',
 'Healthcare',
 'program',
 'Pension',
 'plan',
 'French',
 'standard',
 'annual',
 'leaves',
 'Want',
 'to',
 'know',
 'more',
 '?',
 'Full-time',
 'role',
 ',',
 'to',
 'start',
 'asap',
 'in',
 'Boston',
 '(',
 'MA',
 ',',
 'USA',
 ')',
 'Attractive',
 'compensation',
 '(',
 'depending',
 'on',
 'profile',
 ',',
 'experience',
 ',',
 'and',
 'expertise',
 ')',
 'To',
 'apply',
 ',',
 'send',
 'us',
 'your',
 'resume',
 'and',
 'let',
 'us',
 'know',
 'why',
 'we',
 'could',
 'be',
 'a',
 'great',
 'fit',
 '!',
 'Recognized',
 'by',
 'Wired',
 'as',
 'one',
 'of',
 'Paris',
 '’',
 'hottest',
 'startups',
 'and',
 'proud',
 'member',
 'of',
 'the',
 'Next40',
 ',',
 'here',
 'at',
 'Shift',
 'Technology',
 'we',
 'are',
 'using',
 'advanced',
 'artificial',
 'intelligence',
 'and',
 'data',
 'science',
 'to',
 'help',
 'revolutionize',
 'insurance',
 'from',
 'the',
 'inside',
 'out',
 '.',
 'We',
 'started',
 'with',
 'fraud',
 ',',
 'where',
 'we',
 "'ve",
 'built',
 'a',
 'fast-growing',
 'business',
 'that',
 'is',
 'scaling',
 'globally',
 ';',
 'and',
 'now',
 'we',
 "'re",
 'helping',
 'insurance',
 'companies',
 'to',
 'automate',
 'claims',
 ',',
 'all',
 'the',
 'way',
 'from',
 'the',
 'user',
 'experience',
 'to',
 'the',
 'payment',
 'processing',
 '.']

In [ ]:
tool_keywords1 = ['python', 'pytorch', 'sql', 'mxnet', 'mlflow', 'einstein', 'theano', 'pyspark', 'solr', 'mahout', 
 'cassandra', 'aws', 'powerpoint', 'spark', 'pig', 'sas', 'java', 'nosql', 'docker', 'salesforce', 'scala', 'r',
 'c', 'c++', 'net', 'tableau', 'pandas', 'scikitlearn', 'sklearn', 'matlab', 'scala', 'keras', 'tensorflow', 'clojure',
 'caffe', 'scipy', 'numpy', 'matplotlib', 'vba', 'spss', 'linux', 'azure', 'cloud', 'gcp', 'mongodb', 'mysql', 'oracle', 
 'redshift', 'snowflake', 'kafka', 'javascript', 'qlik', 'jupyter', 'perl', 'bigquery', 'unix', 'react',
 'scikit', 'powerbi', 's3', 'ec2', 'lambda', 'ssrs', 'kubernetes', 'hana', 'spacy', 'tf', 'django', 'sagemaker',
 'seaborn', 'mllib', 'github', 'git', 'elasticsearch', 'splunk', 'airflow', 'looker', 'rapidminer', 'birt', 'pentaho', 
 'jquery', 'nodejs', 'd3', 'plotly', 'bokeh', 'xgboost', 'rstudio', 'shiny', 'dash', 'h20', 'h2o', 'hadoop', 'mapreduce', 
 'hive', 'cognos', 'angular', 'nltk', 'flask', 'node', 'firebase', 'bigtable', 'rust', 'php', 'cntk', 'lightgbm', 
 'kubeflow', 'rpython', 'unixlinux', 'postgressql', 'postgresql', 'postgres', 'hbase', 'dask', 'ruby', 'julia', 'tensor',
# added r packages doesn't seem to impact the result
 'dplyr','ggplot2','esquisse','bioconductor','shiny','lubridate','knitr','mlr','quanteda','dt','rcrawler','caret','rmarkdown',
 'leaflet','janitor','ggvis','plotly','rcharts','rbokeh','broom','stringr','magrittr','slidify','rvest',
 'rmysql','rsqlite','prophet','glmnet','text2vec','snowballc','quantmod','rstan','swirl','datasciencer']


tool_keywords2 = set(['amazon web services', 'google cloud', 'sql server'])

skill_keywords1 = set(['statistics', 'cleansing', 'chatbot', 'cleaning', 'blockchain', 'causality', 'correlation', 'bandit', 'anomaly', 'kpi',
 'dashboard', 'geospatial', 'ocr', 'econometrics', 'pca', 'gis', 'svm', 'svd', 'tuning', 'hyperparameter', 'hypothesis',
 'salesforcecom', 'segmentation', 'biostatistics', 'unsupervised', 'supervised', 'exploratory',
 'recommender', 'recommendations', 'research', 'sequencing', 'probability', 'reinforcement', 'graph', 'bioinformatics',
 'chi', 'knn', 'outlier', 'etl', 'normalization', 'classification', 'optimizing', 'prediction', 'forecasting',
 'clustering', 'cluster', 'optimization', 'visualization', 'nlp', 'c#',
 'regression', 'logistic', 'nn', 'cnn', 'glm',
 'rnn', 'lstm', 'gbm', 'boosting', 'recurrent', 'convolutional', 'bayesian',
 'bayes'])


skill_keywords2 = set(['random forest', 'natural language processing', 'machine learning', 'decision tree', 'deep learning', 'experimental design',
 'time series', 'nearest neighbors', 'neural network', 'support vector machine', 'computer vision', 'machine vision', 'dimensionality reduction', 
 'text analytics', 'power bi', 'a/b testing', 'ab testing', 'chat bot', 'data mining'])


degree_dict = {'bs': 1, 'bachelor': 1, 'undergraduate': 1, 
               'master': 2, 'graduate': 2, 'mba': 2.5, 
               'phd': 3, 'ph.d': 3, 'ba': 1, 'ma': 2,
               'postdoctoral': 4, 'postdoc': 4, 'doctorate': 3}


degree_dict2 = {'advanced degree': 2, 'ms or': 2, 'ms degree': 2, '4 year degree': 1, 'bs/': 1, 'ba/': 1,
                '4-year degree': 1, 'b.s.': 1, 'm.s.': 2, 'm.s': 2, 'b.s': 1, 'phd/': 3, 'ph.d.': 3, 'ms/': 2,
                'm.s/': 2, 'm.s./': 2, 'msc/': 2, 'master/': 2, 'master\'s/': 2, 'bachelor\s/': 1}
degree_keywords2 = set(degree_dict2.keys())

In [ ]:

from nltk import pos_tag
from nltk.stem import PorterStemmer

pos_tag(tool_keywords1)

[('python', 'NN'),
 ('pytorch', 'NN'),
 ('sql', 'JJ'),
 ('mxnet', 'NN'),
 ('mlflow', 'NN'),
 ('einstein', 'NN'),
 ('theano', 'NN'),
 ('pyspark', 'NN'),
 ('solr', 'NN'),
 ('mahout', 'NN'),
 ('cassandra', 'NN'),
 ('aws', 'VBZ'),
 ('powerpoint', 'JJ'),
 ('spark', 'NN'),
 ('pig', 'NN'),
 ('sas', 'NN'),
 ('java', 'NN'),
 ('nosql', 'JJ'),
 ('docker', 'NN'),
 ('salesforce', 'NN'),
 ('scala', 'NN'),
 ('r', 'NN'),
 ('c', 'VBP'),
 ('c++', 'JJ'),
 ('net', 'JJ'),
 ('tableau', 'NN'),
 ('pandas', 'NN'),
 ('scikitlearn', 'NN'),
 ('sklearn', 'NN'),
 ('matlab', 'NN'),
 ('scala', 'NN'),
 ('keras', 'NNS'),
 ('tensorflow', 'JJ'),
 ('clojure', 'NN'),
 ('caffe', 'NN'),
 ('scipy', 'NN'),
 ('numpy', 'JJ'),
 ('matplotlib', 'NN'),
 ('vba', 'NN'),
 ('spss', 'NN'),
 ('linux', 'JJ'),
 ('azure', 'NN'),
 ('cloud', 'NN'),
 ('gcp', 'NN'),
 ('mongodb', 'NN'),
 ('mysql', 'NN'),
 ('oracle', 'NN'),
 ('redshift', 'NN'),
 ('snowflake', 'VBP'),
 ('kafka', 'NN'),
 ('javascript', 'NN'),
 ('qlik', 'NN'),
 ('jupyter', 'NN'),
 ('perl', 'NN'),
 ('bigquery', 'NN'),
 ('unix', 'JJ'),
 ('react', 'JJ'),
 ('scikit', 'NN'),
 ('powerbi', 'NN'),
 ('s3', 'NN'),
 ('ec2', 'NN'),
 ('lambda', 'NN'),
 ('ssrs', 'NN'),
 ('kubernetes', 'VBZ'),
 ('hana', 'JJ'),
 ('spacy', 'NN'),
 ('tf', 'NN'),
 ('django', 'NN'),
 ('sagemaker', 'NN'),
 ('seaborn', 'VBD'),
 ('mllib', 'JJ'),
 ('github', 'NN'),
 ('git', 'NN'),
 ('elasticsearch', 'VBP'),
 ('splunk', 'NN'),
 ('airflow', 'NN'),
 ('looker', 'NN'),
 ('rapidminer', 'NN'),
 ('birt', 'NN'),
 ('pentaho', 'NN'),
 ('jquery', 'NN'),
 ('nodejs', 'NN'),
 ('d3', 'NN'),
 ('plotly', 'RB'),
 ('bokeh', 'VBZ'),
 ('xgboost', 'JJ'),
 ('rstudio', 'NN'),
 ('shiny', 'JJ'),
 ('dash', 'NN'),
 ('h20', 'NN'),
 ('h2o', 'NN'),
 ('hadoop', 'NN'),
 ('mapreduce', 'VBP'),
 ('hive', 'JJ'),
 ('cognos', 'NNS'),
 ('angular', 'JJ'),
 ('nltk', 'JJ'),
 ('flask', 'NN'),
 ('node', 'JJ'),
 ('firebase', 'NN'),
 ('bigtable', 'JJ'),
 ('rust', 'NN'),
 ('php', 'NN'),
 ('cntk', 'NN'),
 ('lightgbm', 'NN'),
 ('kubeflow', 'VB'),
 ('rpython', 'NN'),
 ('unixlinux', 'JJ'),
 ('postgressql', 'NN'),
 ('postgresql', 'NN'),
 ('postgres', 'VBZ'),
 ('hbase', 'JJ'),
 ('dask', 'NN'),
 ('ruby', 'NN'),
 ('julia', 'NN'),
 ('tensor', 'NN'),
 ('dplyr', 'NN'),
 ('ggplot2', 'NN'),
 ('esquisse', 'NN'),
 ('bioconductor', 'NN'),
 ('shiny', 'JJ'),
 ('lubridate', 'NN'),
 ('knitr', 'NN'),
 ('mlr', 'NN'),
 ('quanteda', 'NN'),
 ('dt', 'NN'),
 ('rcrawler', 'NN'),
 ('caret', 'JJ'),
 ('rmarkdown', 'JJ'),
 ('leaflet', 'NN'),
 ('janitor', 'NN'),
 ('ggvis', 'NN'),
 ('plotly', 'RB'),
 ('rcharts', 'VBZ'),
 ('rbokeh', 'NN'),
 ('broom', 'NN'),
 ('stringr', 'NN'),
 ('magrittr', 'NN'),
 ('slidify', 'VB'),
 ('rvest', 'JJS'),
 ('rmysql', 'NN'),
 ('rsqlite', 'NN'),
 ('prophet', 'JJ'),
 ('glmnet', 'NN'),
 ('text2vec', 'NN'),
 ('snowballc', 'NN'),
 ('quantmod', 'NN'),
 ('rstan', 'NN'),
 ('swirl', 'NN'),
 ('datasciencer', 'NN')]

In [ ]:
ps = PorterStemmer()

# process the job description.
def prepare_job_desc(desc):
    # tokenize description.
    tokens = word_tokenize(desc)
        
    # Parts of speech (POS) tag tokens.
    token_tag = pos_tag(tokens)
    include_tags = ['VBN', 'VBD', 'JJ', 'JJS', 'JJR', 'CD', 'NN', 'NNS', 'NNP', 'NNPS']
    filtered_tokens = [tok for tok, tag in token_tag if tag in include_tags]
    
    # stem words.
    stemmed_tokens = [ps.stem(tok).lower() for tok in filtered_tokens]
    return set(stemmed_tokens)

df['job_description_word_set'] = df['job_description'].map(prepare_job_desc)

# process the keywords
tool_keywords1_set = set([ps.stem(tok) for tok in tool_keywords1]) # stem the keywords (since the job description is also stemmed.)
tool_keywords1_dict = {ps.stem(tok):tok for tok in tool_keywords1} # use this dictionary to revert the stemmed words back to the original.

skill_keywords1_set = set([ps.stem(tok) for tok in skill_keywords1])
skill_keywords1_dict = {ps.stem(tok):tok for tok in skill_keywords1}

degree_keywords1_set = set([ps.stem(tok) for tok in degree_dict.keys()])
degree_keywords1_dict = {ps.stem(tok):tok for tok in degree_dict.keys()}

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
tool_keywords1_dict

{'python': 'python',
 'pytorch': 'pytorch',
 'sql': 'sql',
 'mxnet': 'mxnet',
 'mlflow': 'mlflow',
 'einstein': 'einstein',
 'theano': 'theano',
 'pyspark': 'pyspark',
 'solr': 'solr',
 'mahout': 'mahout',
 'cassandra': 'cassandra',
 'aw': 'aws',
 'powerpoint': 'powerpoint',
 'spark': 'spark',
 'pig': 'pig',
 'sa': 'sas',
 'java': 'java',
 'nosql': 'nosql',
 'docker': 'docker',
 'salesforc': 'salesforce',
 'scala': 'scala',
 'r': 'r',
 'c': 'c',
 'c++': 'c++',
 'net': 'net',
 'tableau': 'tableau',
 'panda': 'pandas',
 'scikitlearn': 'scikitlearn',
 'sklearn': 'sklearn',
 'matlab': 'matlab',
 'kera': 'keras',
 'tensorflow': 'tensorflow',
 'clojur': 'clojure',
 'caff': 'caffe',
 'scipi': 'scipy',
 'numpi': 'numpy',
 'matplotlib': 'matplotlib',
 'vba': 'vba',
 'spss': 'spss',
 'linux': 'linux',
 'azur': 'azure',
 'cloud': 'cloud',
 'gcp': 'gcp',
 'mongodb': 'mongodb',
 'mysql': 'mysql',
 'oracl': 'oracle',
 'redshift': 'redshift',
 'snowflak': 'snowflake',
 'kafka': 'kafka',
 'javascript': 'javascript',
 'qlik': 'qlik',
 'jupyt': 'jupyter',
 'perl': 'perl',
 'bigqueri': 'bigquery',
 'unix': 'unix',
 'react': 'react',
 'scikit': 'scikit',
 'powerbi': 'powerbi',
 's3': 's3',
 'ec2': 'ec2',
 'lambda': 'lambda',
 'ssr': 'ssrs',
 'kubernet': 'kubernetes',
 'hana': 'hana',
 'spaci': 'spacy',
 'tf': 'tf',
 'django': 'django',
 'sagemak': 'sagemaker',
 'seaborn': 'seaborn',
 'mllib': 'mllib',
 'github': 'github',
 'git': 'git',
 'elasticsearch': 'elasticsearch',
 'splunk': 'splunk',
 'airflow': 'airflow',
 'looker': 'looker',
 'rapidmin': 'rapidminer',
 'birt': 'birt',
 'pentaho': 'pentaho',
 'jqueri': 'jquery',
 'nodej': 'nodejs',
 'd3': 'd3',
 'plotli': 'plotly',
 'bokeh': 'bokeh',
 'xgboost': 'xgboost',
 'rstudio': 'rstudio',
 'shini': 'shiny',
 'dash': 'dash',
 'h20': 'h20',
 'h2o': 'h2o',
 'hadoop': 'hadoop',
 'mapreduc': 'mapreduce',
 'hive': 'hive',
 'cogno': 'cognos',
 'angular': 'angular',
 'nltk': 'nltk',
 'flask': 'flask',
 'node': 'node',
 'firebas': 'firebase',
 'bigtabl': 'bigtable',
 'rust': 'rust',
 'php': 'php',
 'cntk': 'cntk',
 'lightgbm': 'lightgbm',
 'kubeflow': 'kubeflow',
 'rpython': 'rpython',
 'unixlinux': 'unixlinux',
 'postgressql': 'postgressql',
 'postgresql': 'postgresql',
 'postgr': 'postgres',
 'hbase': 'hbase',
 'dask': 'dask',
 'rubi': 'ruby',
 'julia': 'julia',
 'tensor': 'tensor',
 'dplyr': 'dplyr',
 'ggplot2': 'ggplot2',
 'esquiss': 'esquisse',
 'bioconductor': 'bioconductor',
 'lubrid': 'lubridate',
 'knitr': 'knitr',
 'mlr': 'mlr',
 'quanteda': 'quanteda',
 'dt': 'dt',
 'rcrawler': 'rcrawler',
 'caret': 'caret',
 'rmarkdown': 'rmarkdown',
 'leaflet': 'leaflet',
 'janitor': 'janitor',
 'ggvi': 'ggvis',
 'rchart': 'rcharts',
 'rbokeh': 'rbokeh',
 'broom': 'broom',
 'stringr': 'stringr',
 'magrittr': 'magrittr',
 'slidifi': 'slidify',
 'rvest': 'rvest',
 'rmysql': 'rmysql',
 'rsqlite': 'rsqlite',
 'prophet': 'prophet',
 'glmnet': 'glmnet',
 'text2vec': 'text2vec',
 'snowballc': 'snowballc',
 'quantmod': 'quantmod',
 'rstan': 'rstan',
 'swirl': 'swirl',
 'datascienc': 'datasciencer'}

In [ ]:
df['job_description_word_set'].iloc[10]

{'%',
 '1.5+',
 '10',
 '12',
 '2+',
 'acceler',
 'access',
 'accommod',
 'activ',
 'addit',
 'affili',
 'age',
 'ai',
 'analysi',
 'ancestri',
 'and/or',
 'applic',
 'appropri',
 'background',
 'benefits/perk',
 'bs',
 'cambridg',
 'care',
 'center',
 'characterist',
 'cloud',
 'code',
 'cohort',
 'color',
 'commun',
 'compani',
 'complet',
 'comput',
 'condit',
 'consider',
 'consist',
 'countri',
 'cours',
 'crimin',
 'critic',
 'current',
 'custom',
 'data',
 'data-driven',
 'dataset',
 'decis',
 'degre',
 'develop',
 'disabl',
 'divers',
 'due',
 'edg',
 'electr',
 'employ',
 'energ',
 'engin',
 'england',
 'equal',
 'excel',
 'excit',
 'experi',
 'exposur',
 'express',
 'famili',
 'feedback',
 'field',
 'follow',
 'form',
 'gender',
 'gener',
 'genet',
 'graduat',
 'graphic',
 'ground-break',
 'high-dimension',
 'histori',
 'idea',
 'ident',
 'implement',
 'inclus',
 'inform',
 'integr',
 'intellig',
 'interdisciplinari',
 'issu',
 'key',
 'knowledg',
 'large-scal',
 'last',
 'latest',
 'launch',
 'law',
 'leader',
 'leadership',
 'learn',
 'learning/reinforc',
 'leav',
 'legal',
 'list',
 'live',
 'locat',
 'love',
 'ma',
 'machin',
 'maidap',
 'maker',
 'manag',
 'mani',
 'marit',
 'medic',
 'member',
 'mental',
 'mentor',
 'microsoft',
 'million',
 'models/bayesian',
 'month',
 'ms',
 'nation',
 'natur',
 'nerd',
 'networks/deep',
 'new',
 'next',
 'numer',
 'one',
 'opportun',
 'oral',
 'ordin',
 'organ',
 'orient',
 'origin',
 'other',
 'overal',
 'paradigm',
 'particip',
 'passion',
 'peopl',
 'phd',
 'physic',
 'plu',
 'polit',
 'pregnanc',
 'preparation/etl',
 'probabilist',
 'problem',
 'process',
 'product',
 'program',
 'project',
 'prospect',
 'protect',
 'public',
 'python/r/scala',
 'qualif',
 'qualifi',
 'race',
 'reason',
 'recent',
 'recruit',
 'regard',
 'regul',
 'relat',
 'religion',
 'request',
 'requir',
 'research',
 'respons',
 'result',
 'review',
 's',
 'scienc',
 'scientist',
 'select',
 'series/act',
 'servic',
 'sex',
 'sexual',
 'share',
 'similar',
 'skill',
 'solut',
 'soon-to-b',
 'sport',
 'statist',
 'statu',
 'stay',
 'strong',
 'team',
 'techniqu',
 'technolog',
 'travel',
 'two',
 'varieti',
 'veteran',
 'wide',
 'work',
 'written',
 'year',
 '’'}

In [ ]:
tool_list = []
skill_list = []
degree_list = []

msk = df['city'] != '' 

num_postings = len(df[msk].index)
for i in range(num_postings):
    job_desc = df[msk].iloc[i]['job_description'].lower()
    job_desc_set = df[msk].iloc[i]['job_description_word_set']
    
    # check if the keywords are in the job description. Look for exact match by token.
    tool_words = tool_keywords1_set.intersection(job_desc_set)
    skill_words = skill_keywords1_set.intersection(job_desc_set)
    degree_words = degree_keywords1_set.intersection(job_desc_set)
    
    # check if longer keywords (more than one word) are in the job description. Match by substring.
    j = 0
    for tool_keyword2 in tool_keywords2:
        # tool keywords.
        if tool_keyword2 in job_desc:
            tool_list.append(tool_keyword2)
            j += 1
    
    k = 0
    for skill_keyword2 in skill_keywords2:
        # skill keywords.
        if skill_keyword2 in job_desc:
            skill_list.append(skill_keyword2)
            k += 1
    
    # search for the minimum education.
    min_education_level = 999
    for degree_word in degree_words:
        level = degree_dict[degree_keywords1_dict[degree_word]]
        min_education_level = min(min_education_level, level)
    
    for degree_keyword2 in degree_keywords2:
        # longer keywords. Match by substring.
        if degree_keyword2 in job_desc:
            level = degree_dict2[degree_keyword2]
            min_education_level = min(min_education_level, level)
    
    # label the job descriptions without any tool keywords.
    if len(tool_words) == 0 and j == 0:
        tool_list.append('nothing specified')
    
    # label the job descriptions without any skill keywords.
    if len(skill_words) == 0 and k == 0:
        skill_list.append('nothing specified')
    
    # If none of the keywords were found, but the word degree is present, then assume it's a bachelors level.
    if min_education_level > 500:
        if 'degree' in job_desc:
            min_education_level = 1
    
    tool_list += list(tool_words)
    skill_list += list(skill_words)
    degree_list.append(min_education_level)

In [ ]:
tool_words

{'azur', 'c', 'hadoop', 'java', 'nosql', 'perl', 'python', 'spark', 'sql'}

In [ ]:
tool_list

['python',
 'sql',
 'r',
 'c++',
 'tensor',
 'kera',
 'r',
 'amazon web services',
 'qlik',
 'java',
 'kera',
 'powerbi',
 'sql',
 'spark',
 'tensorflow',
 'python',
 'shini',
 'tableau',
 'aw',
 'r',
 'java',
 'git',
 'hadoop',
 'matlab',
 'c++',
 'python',
 's3',
 'spark',
 'aw',
 'r',
 'net',
 'powerpoint',
 'vba',
 'sa',
 'r',
 'amazon web services',
 'matplotlib',
 'spark',
 'git',
 'sql',
 'cloud',
 'python',
 'seaborn',
 'tableau',
 'panda',
 'aw',
 'r',
 'matlab',
 'cloud',
 'scala',
 'python',
 'spark',
 'r',
 'amazon web services',
 'qlik',
 'java',
 'kera',
 'powerbi',
 'sql',
 'spark',
 'tensorflow',
 'python',
 'shini',
 'tableau',
 'aw',
 'r',
 'python',
 'tensorflow',
 'python',
 'git',
 'cloud',
 'linux',
 'c',
 'cloud',
 'c++',
 'python',
 'd3',
 'sa',
 'aw',
 'r',
 'c',
 'r',
 'python',
 'hadoop',
 'r',
 'java',
 'net',
 'sql',
 'tensorflow',
 'scala',
 'python',
 'spark',
 'nosql',
 'r',
 'matlab',
 'cloud',
 'scala',
 'python',
 'spark',
 'r',
 'python',
 'aw',
 'sql',
 'matlab',
 'cloud',
 'scala',
 'python',
 'spark',
 'r',
 'unix',
 'java',
 'python',
 'sql',
 'python',
 'sql',
 'sagemak',
 'java',
 'git',
 'sql',
 'tensorflow',
 'ec2',
 'scala',
 'h2o',
 'python',
 'shini',
 'aw',
 'r',
 'bigqueri',
 'git',
 'sql',
 'matlab',
 'github',
 'r',
 'nothing specified',
 'google cloud',
 'panda',
 'python',
 'aw',
 'cloud',
 'scipi',
 'numpi',
 'scikit',
 'python',
 'panda',
 'java',
 'python',
 'sql',
 'java',
 'tensorflow',
 'c++',
 'pytorch',
 'python',
 'python',
 'git',
 'aw',
 'numpi',
 'python',
 'panda',
 'github',
 'cloud',
 'unix',
 'java',
 'python',
 'sql',
 'c',
 'java',
 'matlab',
 'c++',
 'python',
 'r',
 'sql',
 'matlab',
 'python',
 'sa',
 'r',
 'python',
 'hadoop',
 'r',
 'java',
 'numpi',
 'tensorflow',
 'c++',
 'scala',
 'pytorch',
 'python',
 'panda',
 'kera',
 'r',
 'sa',
 'tableau',
 'python',
 'r',
 'sql',
 'javascript',
 'cloud',
 'python',
 'unix',
 'panda',
 'aw',
 'matplotlib',
 'sql',
 'hive',
 'python',
 'spark',
 'r',
 'caret',
 'tensorflow',
 'python',
 'panda',
 'github',
 'r',
 'sql',
 'python',
 'panda',
 'mysql',
 'r',
 'amazon web services',
 'java',
 'aw',
 'sql',
 'caret',
 'tensorflow',
 'theano',
 'cloud',
 'mlr',
 'mllib',
 'ec2',
 'mxnet',
 's3',
 'python',
 'caff',
 'cntk',
 'kera',
 'redshift',
 'r',
 'cloud',
 'sa',
 'python',
 'sql',
 'r',
 'sa',
 'python',
 'sql',
 'r',
 'mahout',
 'java',
 'c',
 'splunk',
 'hadoop',
 'postgr',
 'nodej',
 'javascript',
 'angular',
 'react',
 'cloud',
 'c++',
 'kafka',
 'solr',
 'hive',
 'pig',
 'php',
 'mysql',
 'linux',
 'sql',
 'spaci',
 'tensorflow',
 'solr',
 'python',
 'elasticsearch',
 'spark',
 'kera',
 'hadoop',
 'c',
 'java',
 'c++',
 'scala',
 'python',
 'php',
 'r',
 'java',
 'hadoop',
 'sql',
 'tensorflow',
 'c++',
 'hive',
 'python',
 'spark',
 'kera',
 'redshift',
 'r',
 'aw',
 'python',
 'matlab',
 'sql',
 'linux',
 'git',
 'sql',
 'python',
 'spark',
 'linux',
 'git',
 'sql',
 'tensorflow',
 'pytorch',
 'python',
 'jupyt',
 'julia',
 'sql',
 'python',
 'panda',
 'aw',
 'qlik',
 'java',
 'sql',
 'cogno',
 'python',
 'azur',
 'tableau',
 'r',
 'c',
 'python',
 'matlab',
 'c++',
 'python',
 'cloud',
 'r',
 'c',
 'java',
 'sql',
 'c++',
 'python',
 'net',
 'sa',
 'powerpoint',
 'linux',
 'python',
 'hadoop',
 'cloud',
 'qlik',
 'powerbi',
 'sql',
 'python',
 'tableau',
 'sa',
 'r',
 'nothing specified',
 'java',
 'sql',
 'scala',
 'python',
 'spark',
 'r',
 'amazon web services',
 'java',
 'aw',
 'sql',
 'caret',
 'tensorflow',
 'theano',
 'cloud',
 'mlr',
 'mllib',
 'ec2',
 'mxnet',
 's3',
 'python',
 'caff',
 'cntk',
 'kera',
 'redshift',
 'r',
 'python',
 'git',
 'sql',
 'cloud',
 'julia',
 'sql',
 'mongodb',
 'python',
 'sa',
 'r',
 'python',
 'google cloud',
 'git',
 'postgresql',
 'cloud',
 'python',
 'aw',
 'r',
 'sql',
 'hadoop',
 'oracl',
 'hive',
 'pig',
 'javascript',
 'java',
 'python',
 'c',
 'tensorflow',
 'c++',
 'pytorch',
 'python',
 'caff',
 'jupyt',
 'java',
 'spark',
 'git',
 'hadoop',
 'postgresql',
 'spss',
 'tensorflow',
 'c++',
 'kafka',
 'scala',
 'pytorch',
 'python',
 'kubernet',
 'tableau',
 'nosql',
 'docker',
 'nothing specified',
 'sql',
 'hive',
 'panda',
 'sa',
 'r',
 'scipi',
 'hadoop',
 'postgr',
 'numpi',
 'sql',
 'rubi',
 'c++',
 'hive',
 'python',
 'pig',
 'github',
 'r',
 'python',
 'pyspark',
 'kera',
 'hadoop',
 'tensorflow',
 'python',
 'azur',
 'spark',
 'aw',
 'r',
 'google cloud',
 'tensorflow',
 'python',
 'spark',
 'vba',
 'r',
 'rubi',
 'python',
 'kubernet',
 'github',
 'r',
 'sa',
 'python',
 'sql',
 'r',
 'r',
 'oracl',
 'rapidmin',
 'java',
 'hadoop',
 'cloud',
 'hive',
 'python',
 'spark',
 'aw',
 'r',
 'hadoop',
 'hive',
 'python',
 'spark',
 'mysql',
 'nothing specified',
 'hadoop',
 'sql',
 'cloud',
 'python',
 'spark',
 'nosql',
 'r',
 'linux',
 'java',
 'gcp',
 'postgresql',
 'rubi',
 'cloud',
 'c++',
 'python',
 'aw',
 'java',
 'sql',
 'hadoop',
 'javascript',
 'hive',
 'python',
 'spark',
 'sql',
 'cloud',
 'python',
 'azur',
 'tableau',
 'nosql',
 'aw',
 'r',
 'linux',
 'sql',
 'ec2',
 'python',
 'redshift',
 'tableau',
 'aw',
 'lambda',
 'jupyt',
 'java',
 'perl',
 'sql',
 'tensorflow',
 'pytorch',
 'python',
 'rstudio',
 'aw',
 'r',
 'python',
 'sql',
 'cloud',
 'c',
 'sql',
 'powerpoint',
 'spss',
 'matlab',
 'c++',
 'python',
 'sa',
 'r',
 'tensorflow',
 'pytorch',
 'python',
 'kera',
 'r',
 'python',
 'sql',
 'r',
 'sql',
 'shini',
 'python',
 'nosql',
 'r',
 'python',
 'tableau',
 'perl',
 'r',
 'java',
 'sql',
 'scala',
 'airflow',
 'python',
 'docker',
 'net',
 'sa',
 'powerpoint',
 'tensorflow',
 'python',
 'matlab',
 'r',
 'python',
 'git',
 'python',
 'matlab',
 'r',
 'sagemak',
 'scipi',
 'cassandra',
 'numpi',
 'javascript',
 'react',
 'kafka',
 'python',
 'panda',
 'python',
 'sql',
 'sql',
 'looker',
 'oracl',
 'salesforc',
 'scala',
 'python',
 'aw',
 'redshift',
 'r',
 'matlab',
 'cloud',
 'scala',
 'python',
 'spark',
 'r',
 'tensorflow',
 'pytorch',
 'python',
 'spark',
 'kera',
 'sagemak',
 'linux',
 'python',
 'aw',
 'java',
 'cloud',
 'scala',
 'python',
 'sa',
 'aw',
 'r',
 'java',
 'xgboost',
 'nltk',
 'spaci',
 'python',
 'r',
 'jupyt',
 'linux',
 'sql',
 'cloud',
 'python',
 'shini',
 'd3',
 'tableau',
 'nosql',
 'github',
 'ggplot2',
 'r',
 'python',
 'r',
 'git',
 'sql',
 'python',
 'github',
 'r',
 'numpi',
 'hadoop',
 'sql',
 'mapreduc',
 'tensorflow',
 'pytorch',
 'dask',
 'python',
 'elasticsearch',
 'spark',
 'panda',
 'python',
 'matlab',
 'rubi',
 'r',
 'sql',
 'python',
 'spark',
 'panda',
 'r',
 'pytorch',
 'tensorflow',
 'kera',
 'unix',
 'python',
 'sql',
 'julia',
 'tensorflow',
 'c++',
 'pytorch',
 'python',
 'caff',
 'kera',
 'c',
 'java',
 'spark',
 'sql',
 'postgr',
 'javascript',
 'mongodb',
 'ec2',
 'c++',
 'hive',
 'python',
 's3',
 'shini',
 'pig',
 'tableau',
 'nosql',
 'r',
 'sagemak',
 'c',
 'c++',
 'python',
 'azur',
 'aw',
 'tensor',
 'cassandra',
 'hadoop',
 'python',
 'spark',
 'sa',
 'r',
 'java',
 'powerbi',
 'hadoop',
 'sql',
 'azur',
 'spark',
 'numpi',
 'gcp',
 'r',
 'python',
 'tableau',
 'panda',
 'sa',
 'nosql',
 'qlik',
 'jupyt',
 'node',
 'cloud',
 'aw',
 'nothing specified',
 'kera',
 'gcp',
 'tensorflow',
 'hive',
 'python',
 'azur',
 'spark',
 'aw',
 'pyspark',
 'python',
 'sql',
 'java',
 'c++',
 'mxnet',
 'python',
 'tensor',
 'cloud',
 'c',
 'xgboost',
 'net',
 'tensorflow',
 'python',
 'h2o',
 'spark',
 'r',
 'tableau',
 'java',
 'perl',
 'git',
 'sql',
 'c++',
 'python',
 'unix',
 'github',
 'java',
 'git',
 'matlab',
 'scala',
 'python',
 'spark',
 'sa',
 'r',
 'c',
 'sql',
 'python',
 'tableau',
 'r',
 'c',
 'java',
 'scipi',
 'spark',
 'hadoop',
 'numpi',
 'gcp',
 'github',
 'cloud',
 'scala',
 'python',
 'azur',
 'r',
 'aw',
 'mllib',
 'linux',
 'git',
 'sql',
 'tensorflow',
 'pytorch',
 'python',
 'c',
 'java',
 'python',
 'r',
 'sql',
 'powerpoint',
 'linux',
 'java',
 'python',
 'tensorflow',
 'c++',
 'pytorch',
 'python',
 'caff',
 'kera',
 'linux',
 'sql',
 'sagemak',
 'gcp',
 'pytorch',
 'h2o',
 'github',
 'r',
 'tensorflow',
 'scala',
 'python',
 'd3',
 'ggplot2',
 'tableau',
 'nosql',
 'kera',
 'jupyt',
 'shini',
 'theano',
 'aw',
 'jupyt',
 'java',
 'hadoop',
 'sql',
 'gcp',
 'tensorflow',
 'rubi',
 'scala',
 'pytorch',
 'python',
 'ggplot2',
 'spark',
 'panda',
 'aw',
 'r',
 'sa',
 'python',
 'r',
 'powerpoint',
 'sql server',
 'java',
 'sql',
 'javascript',
 'angular',
 'oracl',
 'docker',
 'linux',
 'sa',
 'r',
 'shini',
 'c',
 'python',
 'r',
 'nothing specified',
 'sql',
 'python',
 'tableau',
 'sa',
 'r',
 'c',
 'powerbi',
 'sql',
 'c++',
 'linux',
 'java',
 'gcp',
 'postgresql',
 'rubi',
 'cloud',
 'c++',
 'python',
 'aw',
 'spark',
 'sql',
 'python',
 'hadoop',
 'python',
 'r',
 'pytorch',
 'tensorflow',
 'nothing specified',
 'c',
 'java',
 'hadoop',
 'matlab',
 'c++',
 'hive',
 'python',
 'pig',
 'sa',
 'r',
 'python',
 'c++',
 'java',
 'julia',
 'hadoop',
 'tensorflow',
 'kafka',
 'scala',
 'pytorch',
 'python',
 'spark',
 'github',
 'java',
 'python',
 'matlab',
 'r',
 'r',
 'tableau',
 'python',
 'sql',
 'r',
 'xgboost',
 'tensorflow',
 'python',
 'spark',
 'r',
 'docker',
 'splunk',
 'matlab',
 'docker',
 'python',
 'tableau',
 'r',
 'java',
 'hadoop',
 'gcp',
 'cloud',
 'c++',
 'python',
 'kubernet',
 'azur',
 'django',
 'spark',
 'aw',
 'sql server',
 'spark',
 'sql',
 'powerpoint',
 'mongodb',
 'python',
 'elasticsearch',
 'tableau',
 'sa',
 'r',
 'linux',
 'hadoop',
 'sql',
 'python',
 'sa',
 'aw',
 'r',
 'python',
 'matlab',
 'c++',
 'sa',
 'python',
 'matlab',
 'r',
 'spark',
 'sql',
 'python',
 'hadoop',
 'c',
 'sql',
 'spss',
 'matlab',
 'c++',
 'python',
 'sa',
 'r',
 'python',
 'sql',
 'r',
 'java',
 'sql',
 'hadoop',
 'tensorflow',
 'c++',
 'hive',
 'spark',
 'redshift',
 'python',
 'r',
 'c',
 'java',
 'python',
 'sql server',
 'c',
 'sql',
 'postgresql',
 ...]

#Visualizing the Results

##Top Tools In-Demand

In [ ]:
# create the list of tools.
df_tool = pd.DataFrame(data={'cnt': tool_list})
df_tool = df_tool.replace(tool_keywords1_dict)

# group some of the categories together.
msk = df_tool['cnt'] == 'h20'
df_tool.loc[msk, 'cnt'] = 'h2o'

msk = df_tool['cnt'] == 'aws'
df_tool.loc[msk, 'cnt'] = 'amazon web services'

msk = df_tool['cnt'] == 'gcp'
df_tool.loc[msk, 'cnt'] = 'google cloud'

msk = df_tool['cnt'] == 'github'
df_tool.loc[msk, 'cnt'] = 'git'

msk = df_tool['cnt'] == 'postgressql'
df_tool.loc[msk, 'cnt'] = 'postgres'

msk = df_tool['cnt'] == 'tensor'
df_tool.loc[msk, 'cnt'] = 'tensorflow'

df_tool_top50 = df_tool['cnt'].value_counts().reset_index().rename(columns={'index': 'tool'}).iloc[:50]

In [ ]:
df_tool_top50

                   tool   cnt
0                python  1651
1                   sql  1077
2                     r  1035
3                 spark   559
4                 cloud   530
5   amazon web services   527
6                  java   513
7            tensorflow   427
8                hadoop   401
9     nothing specified   378
10                  sas   354
11              tableau   339
12                  c++   299
13                scala   272
14         google cloud   244
15              pytorch   242
16                  git   213
17                    c   204
18                azure   204
19                 hive   192
20               pandas   169
21               matlab   168
22                keras   159
23                nosql   145
24           powerpoint   139
25                linux   139
26               docker   132
27           javascript   127
28                kafka   110
29                numpy   106
30             redshift   104
31                mysql    93
32           kubernetes    92
33               oracle    86
34                   s3    83
35                caffe    83
36              mongodb    80
37                 unix    79
38           sql server    78
39           salesforce    77
40                 spss    68
41              jupyter    68
42                 perl    64
43            cassandra    62
44                  pig    61
45                scipy    59
46              powerbi    58
47               looker    56
48              airflow    53
49                  net    52

In [ ]:
# visualize the tools.
layout = dict(
    title='Tools For Data Scientists',
    yaxis=dict(
        title='% of job postings',
        tickformat=',.0%',
    )
)

fig = go.Figure(layout=layout)
fig.add_trace(go.Bar(
    x=df_tool_top50['tool'],
    y=df_tool_top50['cnt']/num_postings
))

# iplot(fig)
fig.show(renderer="colab")

##Top Skills In-Demand

In [ ]:
# create the list of skills/knowledge.
df_skills = pd.DataFrame(data={'cnt': skill_list})
df_skills = df_skills.replace(skill_keywords1_dict)

# group some of the categories together.
msk = df_skills['cnt'] == 'nlp'
df_skills.loc[msk, 'cnt'] = 'natural language processing'

msk = df_skills['cnt'] == 'convolutional'
df_skills.loc[msk, 'cnt'] = 'convolutional neural network'

msk = df_skills['cnt'] == 'cnn'
df_skills.loc[msk, 'cnt'] = 'convolutional neural network'

msk = df_skills['cnt'] == 'recurrent'
df_skills.loc[msk, 'cnt'] = 'recurrent neural network'

msk = df_skills['cnt'] == 'rnn'
df_skills.loc[msk, 'cnt'] = 'recurrent neural network'

msk = df_skills['cnt'] == 'knn'
df_skills.loc[msk, 'cnt'] = 'nearest neighbors'

msk = df_skills['cnt'] == 'svm'
df_skills.loc[msk, 'cnt'] = 'support vector machine'

msk = df_skills['cnt'] == 'machine vision'
df_skills.loc[msk, 'cnt'] = 'computer vision'

msk = df_skills['cnt'] == 'ab testing'
df_skills.loc[msk, 'cnt'] = 'a/b testing'

df_skills_top50 = df_skills['cnt'].value_counts().reset_index().rename(columns={'index': 'skill'}).iloc[:50]

In [ ]:
# visualize the skills.
layout = dict(
    title='Skills For Data Scientists',
    yaxis=dict(
        title='% of job postings',
        tickformat=',.0%',
    )
)

fig = go.Figure(layout=layout)
fig.add_trace(go.Bar(
    x=df_skills_top50['skill'],
    y=df_skills_top50['cnt']/num_postings
))

fig.show(renderer="colab")

##Minimum Education Required

In [ ]:
# create the list of degree.
df_degrees = pd.DataFrame(data={'cnt': degree_list})
df_degrees['degree_type'] = ''


msk = df_degrees['cnt'] == 1
df_degrees.loc[msk, 'degree_type'] = 'bachelors'

msk = df_degrees['cnt'] == 2
df_degrees.loc[msk, 'degree_type'] = 'masters'

msk = df_degrees['cnt'] == 3
df_degrees.loc[msk, 'degree_type'] = 'phd'

msk = df_degrees['cnt'] == 4
df_degrees.loc[msk, 'degree_type'] = 'postdoc'

msk = df_degrees['cnt'] == 2.5
df_degrees.loc[msk, 'degree_type'] = 'mba'

msk = df_degrees['cnt'] > 500
df_degrees.loc[msk, 'degree_type'] = 'not specified'


df_degree_cnt = df_degrees['degree_type'].value_counts().reset_index().rename(columns={'index': 'degree'}).iloc[:50]

In [ ]:
# visualize the degrees.
layout = dict(
    title='Minimum Education For Data Scientists',
    yaxis=dict(
        title='% of job postings',
        tickformat=',.0%',
    )
)

fig = go.Figure(layout=layout)
fig.add_trace(go.Bar(
    x=df_degree_cnt['degree'],
    y=df_degree_cnt['degree_type']/num_postings
))

fig.show(renderer="colab")